# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('category_type', models.IntegerField(choices=[(1, '学校'), (2, '学院'), (3, '专业')], help_text='类目级别', verbose_name='类目级别')),
                ('province', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='区域')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='详细地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='schools.Schools', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
    ]
